"""add user session model

Revision ID: 2ce8a8368f37
Revises: 30a58307d963
Create Date: 2026-05-21 11:27:15.720646

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ce8a8368f37"
down_revision: Union[str, Sequence[str], None] = "30a58307d963"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_sessions",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "refresh_token_hash",
            sa.String(length=1024),
            nullable=False,
        ),
        sa.Column(
            "access_token_jti", sa.String(length=36), nullable=False
        ),
        sa.Column(
            "device_info", sa.String(length=300), nullable=True
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_sessions_access_token_jti"),
        "user_sessions",
        ["access_token_jti"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_sessions_refresh_token_hash"),
        "user_sessions",
        ["refresh_token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_sessions_user_id"),
        "user_sessions",
        ["user_id"],
        unique=False,
    )
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id", sa.INTEGER(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "rf_token",
            sa.VARCHAR(length=1024),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("refresh_tokens_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("refresh_tokens_pkey")
        ),
        sa.UniqueConstraint(
            "rf_token",
            name=op.f("refresh_tokens_rf_token_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_index(
        op.f("ix_user_sessions_user_id"), table_name="user_sessions"
    )
    op.drop_index(
        op.f("ix_user_sessions_refresh_token_hash"),
        table_name="user_sessions",
    )
    op.drop_index(
        op.f("ix_user_sessions_access_token_jti"),
        table_name="user_sessions",
    )
    op.drop_table("user_sessions")
    # ### end Alembic commands ###
