"""add user display_name

Revision ID: 30a58307d963
Revises: 8cdae135bd10
Create Date: 2026-05-19 11:00:22.991875

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30a58307d963"
down_revision: Union[str, Sequence[str], None] = "8cdae135bd10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "display_name", sa.String(length=60), nullable=True
        ),
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=60),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users",
        "username",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=60),
        existing_nullable=False,
    )
    op.drop_column("users", "display_name")
    # ### end Alembic commands ###
