"""add rating photo model

Revision ID: 6f4000418871
Revises: 2ce8a8368f37
Create Date: 2026-05-21 14:42:06.619086

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f4000418871"
down_revision: Union[str, Sequence[str], None] = "2ce8a8368f37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photo_ratings",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "rating >= 1 AND rating <= 5",
            name="ck_photo_ratings_rating_1_5",
        ),
        sa.ForeignKeyConstraint(
            ["photo_id"], ["photos.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "photo_id",
            "user_id",
            name="uq_photo_ratings_photo_id_user_id",
        ),
    )
    op.create_index(
        op.f("ix_photo_ratings_photo_id"),
        "photo_ratings",
        ["photo_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_photo_ratings_user_id"),
        "photo_ratings",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_photo_ratings_user_id"), table_name="photo_ratings"
    )
    op.drop_index(
        op.f("ix_photo_ratings_photo_id"), table_name="photo_ratings"
    )
    op.drop_table("photo_ratings")
    # ### end Alembic commands ###
