"""add unique constraint to password reset tokens user_id

Revision ID: a0017df77a24
Revises: 6f4000418871
Create Date: 2026-05-24 12:53:21.056371

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0017df77a24"
down_revision: Union[str, Sequence[str], None] = "6f4000418871"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_password_reset_tokens_user_id",
        "password_reset_tokens",
        ["user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_password_reset_tokens_user_id",
        "password_reset_tokens",
        type_="unique",
    )
    # ### end Alembic commands ###
