"""add photos, tags, transformation photos

Revision ID: e2a8f3a40bc1
Revises: 1ff28033510d
Create Date: 2026-05-13 15:10:34.488086

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2a8f3a40bc1"
down_revision: Union[str, Sequence[str], None] = "1ff28033510d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tags_name"), "tags", ["name"], unique=True
    )
    op.create_table(
        "photos",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "description", sa.String(length=300), nullable=True
        ),
        sa.Column(
            "image_url", sa.String(length=1024), nullable=False
        ),
        sa.Column("public_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image_url"),
    )
    op.create_index(
        op.f("ix_photos_id"), "photos", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_photos_owner_id"),
        "photos",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_photos_public_id"),
        "photos",
        ["public_id"],
        unique=True,
    )
    op.create_table(
        "photo_tags",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["photo_id"], ["photos.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "photo_id", "tag_id", name="uq_photo_tag"
        ),
    )
    op.create_table(
        "photo_transformations",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "transformation_type",
            sa.Enum(
                "crop",
                "resize",
                "grayscale",
                "rotate",
                "blur",
                name="transformationtype",
            ),
            nullable=False,
        ),
        sa.Column("transformation_params", sa.JSON(), nullable=False),
        sa.Column(
            "transformed_url", sa.String(length=1024), nullable=False
        ),
        sa.Column(
            "qr_code_url", sa.String(length=1024), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["photo_id"], ["photos.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transformed_url"),
    )
    op.create_index(
        op.f("ix_photo_transformations_photo_id"),
        "photo_transformations",
        ["photo_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_photo_transformations_user_id"),
        "photo_transformations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_photo_transformations_user_id"),
        table_name="photo_transformations",
    )
    op.drop_index(
        op.f("ix_photo_transformations_photo_id"),
        table_name="photo_transformations",
    )
    op.drop_table("photo_transformations")
    op.drop_table("photo_tags")
    op.drop_index(op.f("ix_photos_public_id"), table_name="photos")
    op.drop_index(op.f("ix_photos_owner_id"), table_name="photos")
    op.drop_index(op.f("ix_photos_id"), table_name="photos")
    op.drop_table("photos")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
